// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGame() {
  return window['go']['main']['App']['AddGame']();
}

export function GetCover(arg1) {
  return window['go']['main']['App']['GetCover'](arg1);
}

export function GetDownloads() {
  return window['go']['main']['App']['GetDownloads']();
}

export function GetGames(arg1) {
  return window['go']['main']['App']['GetGames'](arg1);
}

export function GetLibrary() {
  return window['go']['main']['App']['GetLibrary']();
}

export function ScrapeTorrents(arg1) {
  return window['go']['main']['App']['ScrapeTorrents'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}

export function StartGame(arg1) {
  return window['go']['main']['App']['StartGame'](arg1);
}
