// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddGame():Promise<boolean>;

export function GetLibrary():Promise<{[key: number]: main.Game}>;

export function StartGame(arg1:number):Promise<boolean>;
